name: Safe Commit Bot

on:
  schedule:
    - cron: '0 9 * * *'  # щодня о 09:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run commit bot script
        run: |
          python commit_bot.py

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add journal.md || true
          git add .
          git commit -m "chore: automated daily updates" || echo "No changes to commit"

      - name: Push
        run: git push origin HEAD:${{ github.ref_name }}
